---
- name: Ensure jdks folder exists
  file:
    path: ~/.local/jdks/
    state: directory

# TODO update to latest
# TODO how to best configure JAVA_HOME? use jenv?
- name: Get latest JDK 11
  unarchive: 
    src: "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2021-05-07-07-34/OpenJDK11U-jdk_x64_linux_hotspot_2021-05-07-07-34.tar.gz"
    dest: ~/.local/jdks/
    creates: ~/.local/jdks/jdk-11.0.12+
    remote_src: true

- name: Ensure LSP related folders exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.local/share/eclipse
    - ~/.local/share/lombok
    - ~/code/eclipse

- name: Clone Eclipse Java LSP
  git:
    repo: https://github.com/eclipse/eclipse.jdt.ls
    dest: ~/code/eclipse/eclipse.jdt.ls
    force: true
  register: java_lsp_changed

# TODO automate Java LSP setup
# TODO which environment?
# - name: Build Eclipse Java LSP
#   command: ./mvnw clean verify -DskipTests
#   environment:
#     JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
#   args:
#     chdir: ~/code/eclipse/eclipse.jdt.ls
#   when: java_lsp_changed.before != java_lsp_changed.after
