---
- name: Ensure jdks folder exists
  file:
    path: ~/.local/jdks/
    state: directory
- name: Get latest release of a public repository
  github_release:
    user: AdoptOpenJDK
    repo: openjdk11-binaries
    action: latest_release
  # register: jdk11_latest 
- name: Get latest JDK 11
  unarchive: 
    src: "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/{{ jdk11_latest['tag'] }}/OpenJDK11U-jdk_x64_linux_hotspot_{{ jdk11_latest['tag'] | replace('jdk11u-', '')  }}.tar.gz"
    dest: ~/.local/jdks/
    remote_src: true
