---
- name: Install JDKs
  import_tasks: jdks.yml

- name: Ensure LSP related folders exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.local/share/eclipse
    - ~/.local/share/lombok
    - ~/code/lsp

- name: Install lombok
  get_url:
    url: https://projectlombok.org/downloads/lombok.jar
    dest: ~/.local/share/lombok
    mode: '0660'

# TODO they do not provide a latest release
# I can therefore not use the Github API to fetch the latest release
# information, compute its version and check whether its a new one
# how else can I get the latest release?
- name: Clone Eclipse Java LSP
  git:
    repo: https://github.com/eclipse/eclipse.jdt.ls
    dest: ~/code/lsp/eclipse.jdt.ls
    force: true
    version: v1.5.0
  register: java_lsp_changed

# TODO can the jdks.yml tasks register a dictionary with all the JAVA_HOME's
# it installed?
- name: Build Eclipse Java LSP
  command: ./mvnw --batch-mode --no-transfer-progress --threads 6 clean package -DskipTests -Dmaven.test.skip=true
  environment:
    JAVA_HOME: '/usr/lib/jvm/java-11-openjdk-amd64/'
  args:
    chdir: ~/code/lsp/eclipse.jdt.ls
  when: java_lsp_changed.before != java_lsp_changed.after

- name: Configure Maven
  import_tasks: maven.yml
