---
- name: Install JDKs
  import_tasks: jdks.yml

- name: Ensure LSP related folders exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.local/share/eclipse
    - ~/.local/share/lombok
    - ~/code/eclipse

- name: Clone Eclipse Java LSP
  git:
    repo: https://github.com/eclipse/eclipse.jdt.ls
    dest: ~/code/eclipse/eclipse.jdt.ls
    force: true
  register: java_lsp_changed

# TODO automate Java LSP setup
# TODO which environment?
# - name: Build Eclipse Java LSP
#   command: ./mvnw clean verify -DskipTests
#   environment:
#     JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
#   args:
#     chdir: ~/code/eclipse/eclipse.jdt.ls
#   when: java_lsp_changed.before != java_lsp_changed.after
