---
- name: Install packages
  become: true
  apt:
    pkg:
      - font-manager
      - gnome-shell-pomodoro
      - gnome-software-plugin-flatpak
      - gthumb

- name: Install snaps
  become: true
  snap:
    name:
      - snap-store
      - orchis-themes
      - gtk-common-themes
      - foliate


- name: Connect snaps with theme
  shell: for i in $(snap connections | grep gtk-common-themes:gtk-3-themes | awk '{print $2}'); do sudo snap connect $i orchis-themes:gtk-3-themes; done
  args:
    executable: /bin/sh

- name: Clone theme
  git:
    repo: https://github.com/vinceliuice/Orchis-theme
    dest: ~/code/themes/orchis-teme
    force: true
  register: theme_changed

- name: Install theme
  command: ./install.sh --theme purple
  args:
    chdir: ~/code/themes/orchis-teme
  when: theme_changed.before != theme_changed.after

- name: Install newer firefox
  import_tasks: firefox.yml
