---
# https://www.google.com/linuxrepositories/
- name: Download Google Linux signing key
  become: true
  get_url:
    url: "{{ google_gpg_key_url }}"
    dest: /usr/share/keyrings/google.asc
    mode: '0644'
    force: false

- name: Verify Google GPG key fingerprint
  command: gpg --show-keys --with-fingerprint /usr/share/keyrings/google.asc
  register: google_gpg_output
  changed_when: false

- name: Check Google GPG key fingerprint
  assert:
    that:
      # Normalize spacing - GPG output has inconsistent spaces between fingerprint segments
      - "google_gpg_key_fingerprint | replace(' ', '') in google_gpg_output.stdout | replace(' ', '')"
    fail_msg: "Google GPG key fingerprint verification failed"

- name: Add Google Chrome apt repository
  become: true
  apt_repository:
    repo: "{{ google_apt_repo }}"
    state: present
    update_cache: true

- name: Install Google Chrome
  become: true
  apt:
    pkg:
      - google-chrome-stable
    state: "{{ apt_package_state }}"