live_config_reload = true

[colors.bright]
black = "#545c8c"
blue = "#589ec6"
cyan = "#59b6b6"
green = "#7cbe8c"
magenta = "#b871b8"
red = "#dc6f7a"
white = "#ffffff"
yellow = "#a8a384"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.dim]
black = "#545c8c"
blue = "#589ec6"
cyan = "#59b6b6"
green = "#7cbe8c"
magenta = "#b871b8"
red = "#dc6f7a"
white = "#ffffff"
yellow = "#a8a384"

[colors.normal]
black = "#545c8c"
blue = "#589ec6"
cyan = "#59b6b6"
green = "#7cbe8c"
magenta = "#5e3e5e"
red = "#dc6f7a"
white = "#ffffff"
yellow = "#a8a384"

[colors.primary]
background = "#222433"
dim_foreground = "#8085a6"
foreground = "#9ea3c0"

[colors.selection]
background = "#4c566a"
text = "#d8dee9"

[colors.vi_mode_cursor]
background = "#4c566a"
text = "#d8dee9"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Gintronic Nerd Font"
style = "Bold"

[font.italic]
family = "Gintronic Nerd Font"
style = "Medium Italic"

[font.normal]
family = "Gintronic Nerd Font"
style = "Medium"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[schemes.dogrun.bright]
black = "#545c8c"
blue = "#589ec6"
cyan = "#59b6b6"
green = "#7cbe8c"
magenta = "#b871b8"
red = "#dc6f7a"
white = "#ffffff"
yellow = "#a8a384"

[schemes.dogrun.cursor]
cursor = "CellForeground"
text = "CellBackground"

[schemes.dogrun.dim]
black = "#545c8c"
blue = "#589ec6"
cyan = "#59b6b6"
green = "#7cbe8c"
magenta = "#b871b8"
red = "#dc6f7a"
white = "#ffffff"
yellow = "#a8a384"

[schemes.dogrun.normal]
black = "#545c8c"
blue = "#589ec6"
cyan = "#59b6b6"
green = "#7cbe8c"
magenta = "#5e3e5e"
red = "#dc6f7a"
white = "#ffffff"
yellow = "#a8a384"

[schemes.dogrun.primary]
background = "#222433"
dim_foreground = "#8085a6"
foreground = "#9ea3c0"

[schemes.dogrun.selection]
background = "#4c566a"
text = "#d8dee9"

[schemes.dogrun.vi_mode_cursor]
background = "#4c566a"
text = "#d8dee9"

[schemes.nord.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[schemes.nord.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[schemes.nord.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[schemes.nord.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[schemes.nord.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[schemes.nord.search.bar]
background = "#434c5e"
foreground = "#d8dee9"

[schemes.nord.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[schemes.nord.selection]
background = "#4c566a"
text = "#d8dee9"

[schemes.nord.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[scrolling]
history = 10000
multiplier = 3

[window]
startup_mode = "Fullscreen"

[window.dimensions]
columns = 90
lines = 30

[window.padding]
x = 4
y = 4
