live_config_reload = true

[colors.bright]
black = "#545c8c"
blue = "#589ec6"
cyan = "#59b6b6"
green = "#7cbe8c"
magenta = "#b871b8"
red = "#dc6f7a"
white = "#ffffff"
yellow = "#a8a384"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.dim]
black = "#545c8c"
blue = "#589ec6"
cyan = "#59b6b6"
green = "#7cbe8c"
magenta = "#b871b8"
red = "#dc6f7a"
white = "#ffffff"
yellow = "#a8a384"

[colors.normal]
black = "#545c8c"
blue = "#589ec6"
cyan = "#59b6b6"
green = "#7cbe8c"
magenta = "#5e3e5e"
red = "#dc6f7a"
white = "#ffffff"
yellow = "#a8a384"

[colors.primary]
background = "#222433"
dim_foreground = "#8085a6"
foreground = "#9ea3c0"

[colors.selection]
background = "#4c566a"
text = "#d8dee9"

[colors.vi_mode_cursor]
background = "#4c566a"
text = "#d8dee9"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Gintronic Nerd Font"
style = "Bold"

[font.italic]
family = "Gintronic Nerd Font"
style = "Medium Italic"

[font.normal]
family = "Gintronic Nerd Font"
style = "Medium"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[scrolling]
history = 10000
multiplier = 3

[window]
startup_mode = "Fullscreen"

[window.dimensions]
columns = 90
lines = 30

[window.padding]
x = 4
y = 4
