live_config_reload = true

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.bright]
black = "#545c8c"
blue = "#589ec6"
cyan = "#59b6b6"
green = "#7cbe8c"
magenta = "#b871b8"
red = "#ff9494"
white = "#ffffff"
yellow = "#a8a384"

[colors.dim]
black = "#545c8c"
blue = "#589ec6"
cyan = "#59b6b6"
green = "#7cbe8c"
magenta = "#b871b8"
red = "#ff9494"
white = "#ffffff"
yellow = "#a8a384"

[colors.normal]
black = "#545c8c"
blue = "#589ec6"
cyan = "#59b6b6"
green = "#7cbe8c"
magenta = "#5e3e5e"
red = "#ff9494"
white = "#ffffff"
yellow = "#a8a384"

[colors.primary]
background = "#222433"
dim_foreground = "#8085a6"
foreground = "#9ea3c0"

[colors.selection]
background = "#4c566a"
text = "#d8dee9"

[colors.vi_mode_cursor]
background = "#4c566a"
text = "#d8dee9"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Gintronic Nerd Font"
style = "Bold"

[font.italic]
family = "Gintronic Nerd Font"
style = "Medium Italic"

[font.normal]
family = "Gintronic Nerd Font"
style = "Medium"

[[keyboard.bindings]]
key = "Return"
mods = "Control"
action = "ToggleFullscreen"

# allows me to use different mappings for <tab> and <C-i>
# does not work inside tmux due to
# https://github.com/tmux/tmux/issues/2704
# get some extended keys config which at least were in yaml and convert it to toml
# alacritty migrate --config-file keys.yaml
[[keyboard.bindings]]
key = "I"
mods = "Control"
chars = "\u001B[105;5u"

[scrolling]
history = 10000
multiplier = 3

[shell]
args = ["--login", "-c", "source ~/.zshrc; tmux attach || tmux"]
program = "/usr/bin/zsh"

[window]
startup_mode = "Fullscreen"

[window.dimensions]
columns = 90
lines = 30

[window.padding]
x = 4
y = 4

# this is the default hint but mapped to O as U underlines URL without showing an alphabet char. not
# sure why. opening via the mouse does work by default though.
[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[hints.enabled]]
action = "Copy"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "Y", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
