---
- name: Clean up previous build
  file:
    path: ~/code/alacritty/alacritty/target/release/alacritty
    state: absent

- name: Build alacritty
  command: "{{ lookup('env', 'HOME') }}/.cargo/bin/cargo build --release"
  args:
    chdir: ~/code/alacritty/alacritty
    creates: target/release/alacritty

# https://github.com/alacritty/alacritty/blob/master/INSTALL.md#post-build
# backup binary just in case my ansible automation has some flaws
- name: Install alacritty binary
  become: true
  copy:
    src: "{{ lookup('env', 'HOME') }}/code/alacritty/alacritty/target/release/alacritty"
    dest: /usr/local/bin/alacritty
    owner: root
    group: root
    mode: "0755"
    backup: yes

- name: Install alacritty logo
  become: true
  copy:
    src: "{{ lookup('env', 'HOME') }}/code/alacritty/alacritty/extra/logo/alacritty-term.svg"
    dest: /usr/share/pixmaps/Alacritty.svg
    owner: root
    group: root
    mode: "0644"

- name: Install alacritty desktop file
  become: true
  command: desktop-file-install extra/linux/Alacritty.desktop
  args:
    chdir: "{{ lookup('env', 'HOME') }}/code/alacritty/alacritty"

- name: Update desktop database
  become: true
  command: update-desktop-database

- name: Update man pages
  become: true
  file:
    path: /usr/local/share/man/man1
    state: directory
    recurse: yes
# TODO
# https://github.com/alacritty/alacritty/blob/master/INSTALL.md#zsh
