# https://github.com/alacritty/alacritty/blob/master/INSTALL.md#install-the-rust-compiler-with-rustup
- name: Download rust installer
  get_url:
    url: https://sh.rustup.rs 
    dest: /tmp/rust_installer.sh
    mode: '0555'

- name: Install rust compiler
  shell:
    cmd: /tmp/rust_installer.sh -y -q

- name: Ensure correct rust compiles is installed (1)
  shell: rustup override set stable

- name: Ensure correct rust compiles is installed (2)
  shell: rustup update stable

# https://github.com/alacritty/alacritty/blob/master/INSTALL.md#debianubuntu
- name: Install newer cmake
  pip:
    name: cmake

- name: Create symbolic link to cmake
  file:
    src: /usr/local/bin/cmake
    dest: /usr/bin/cmake
    state: link

- name: Install pre-requisite packages
  apt:
    pkg:
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
      - python3

- name: Clone alacritty
  git:
    repo: https://github.com/alacritty/alacritty
    dest: ~/code/alacritty/alacritty
    version: v0.9.0
    force: true
  register: alacritty_changed

- name: Build alacritty
  import_tasks: build.yml
  when: alacritty_changed.before != alacritty_changed.after
