alias gl='git log --oneline --decorate --all --graph'
alias gs='git status'
alias gso='git show'
alias ga='git add'
alias gd='git diff'
alias gds='git diff --staged'
alias gb='git branch'
alias gbd='git branch -d'
alias gbD='git branch -D'
alias gf='git fetch'
alias gfu='git fetch upstream'
alias gfb='git fetch bgevam'
alias gp='git push'
alias gpf='git push --force'
alias gc='git commit'
alias gcm='git commit -m'
alias gcia='git commit --amend'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gr='git rebase'
alias grm='git rebase master'
alias gpum='git pull --rebase upstream master'
alias grpo='git remote prune origin'
alias grpb='git remote prune bgevam'

alias mcp='mvn clean package'
alias mcps='mvn clean package -Dmaven.test.skip=true'

