alias ga='git add'
alias gb='git branch'
alias gbd='git branch -d'
alias gbD='git branch -D'
alias gc='git commit'
alias gcm='git commit -m'
alias gca='git commit --amend'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcod='git checkout -- :/'
alias gd='git diff'
alias gds='git diff --staged'
alias gf='git fetch'
alias gfu='git fetch upstream'
alias gfb='git fetch bgevam'
alias gl='git log --oneline --decorate --all --graph'
alias gm='git merge'
alias gp='git push'
alias gpf='git push --force'
alias gpl='git pull'
alias gplrum='git pull --rebase upstream master'
alias gr='git rebase'
alias grm='git rebase master'
alias gre='git remote -vv'
alias grepo='git remote prune origin'
alias grepb='git remote prune bgevam'
alias gs='git status'
alias gso='git show'
alias gsos='git show --stat'

alias mcp='mvn clean package'
alias mcps='mvn clean package -Dmaven.test.skip=true'

alias vs='vagrant status'
alias vu='vagrant up'
alias vssh='vagrant ssh'
alias vd='vagrant destroy -f'
