#!/usr/bin/env bash

# see https://github.com/mfussenegger/nvim-jdtls#language-server-installation
BASE="$HOME/code/eclipse/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository"
JAR="$BASE/plugins/org.eclipse.equinox.launcher_*.jar"
GRADLE_HOME=$HOME/gradle /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64/bin/java \
  -Declipse.application=org.eclipse.jdt.ls.core.id1 \
  -Dosgi.bundles.defaultStartLevel=4 \
  -Declipse.product=org.eclipse.jdt.ls.core.product \
  -Dlog.protocol=true \
  -Dlog.level=ALL \
  -Xms1g \
  -Xmx2G \
  -jar $(echo "$JAR") \
  -configuration "$BASE/config_linux" \
  -data "${1:-$HOME/.local/share/eclipse}" \
  --add-modules=ALL-SYSTEM \
  --add-opens java.base/java.util=ALL-UNNAMED \
  --add-opens java.base/java.lang=ALL-UNNAMED

