---
- name: Install stow
  become: true
  apt:
    state: latest
    name: stow
- name: Ensure folders exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/bin
    - ~/.config/git
    - ~/.config/nvim
- name: Create symlinks into dotfiles
  shell: stow alacritty alias bat bin git shell vim
  args:
    chdir: ~/.dotfiles
