---
- name: Install stow
  become: yes
  apt:
    state: latest
    name: stow

- name: Ensure folders exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/bin
    - ~/.config/git

- name: Create symlinks into dotfiles
  command: stow --target ~/ alias bin git fd psql
  args:
    chdir: ~/code/dotfiles
