---
- name: Install stow
  become: true
  apt:
    state: latest
    name: stow

- name: Ensure folders exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/bin
    - ~/.config/git
    - ~/.config/fd
    - ~/.config/rg
    - ~/.config/yazi

- name: Create symlinks into dotfiles
  command:
    argv:
      - stow
      - --target
      - ~/
      - --restow
      - --stow
      - alias
      - bin
      - claude
      - dunst
      - fd
      - fuzzel
      - git
      - intellij
      - kanshi
      - psql
      - rg
      - shell
      - sway
      - waybar
      - xdg-desktop-portal
      - yazi
  args:
    chdir: ~/code/dotfiles
