---
- name: Install stow
  become: true
  apt:
    state: latest
    name: stow

- name: Ensure folders exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/bin
    - ~/.config/git
    - ~/.config/fd
    - ~/.config/rg

- name: Create symlinks into dotfiles
  command:
    argv:
      - stow
      - --target
      - ~/
      - --restow
      - --stow
      - alias
      - claude
      - bin
      - fd
      - git
      - intellij
      - psql
      - rg
      - i3
      - i3status
  args:
    chdir: ~/code/dotfiles
