
# https://github.com/alacritty/alacritty/blob/master/INSTALL.md#debianubuntu
- name: Install pre-requisite packages
  become: true
  apt:
    pkg:
      - cmake
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
      - python3
      - stow # required for linking the ~/.config/alacritty

- name: Ensure config folder exists
  file:
    path: ~/.config/alacritty
    state: directory

- name: Create symlinks into dotfiles
  command: stow --target ~/ alacritty
  args:
    chdir: ~/code/dotfiles

- name: Fetch latest release information
  uri:
    url: https://api.github.com/repos/alacritty/alacritty/releases/latest
    return_content: true
  register: alacritty_release_json

- name: "Clone alacritty {{ alacritty_release_json.json.tag_name }}"
  git:
    repo: https://github.com/alacritty/alacritty
    dest: ~/code/alacritty/alacritty
    version: "{{ alacritty_release_json.json.tag_name }}"
    force: true
  register: alacritty_changed

- name: Build alacritty
  import_tasks: build.yml
  when: alacritty_changed.before != alacritty_changed.after
