- name: Install packages
  become: yes
  apt:
    pkg:
      - tmux
      - stow # required for linking the config

- name: Create symlinks into dotfiles
  shell: stow --target ~/ tmux
  args:
    chdir: ~/code/dotfiles

