- name: Install zig
  become: true
  snap:
    name: zig
    classic: true
    channel: beta

# https://ghostty.org/docs/install/build#debian-and-ubuntu
- name: Install pre-requisite packages
  become: true
  apt:
    pkg:
      - libgtk-4-dev
      - libadwaita-1-dev
      - git
      - stow # required for linking the config

- name: Clone
  git:
    repo: https://github.com/ghostty-org/ghostty
    dest: ~/code/ghostty/ghostty
    version: tip
    force: true
  register: ghostty_changed

- name: Build
  import_tasks: build.yml
  when: ghostty_changed.before != ghostty_changed.after

- name: Ensure config folder exists
  file:
    path: ~/.config/ghostty
    state: directory

- name: Create symlinks into dotfiles
  command: stow --target ~/ ghostty
  args:
    chdir: ~/code/dotfiles
