- name: Install zig
  become: true
  snap:
    name: zig
    classic: true
    channel: beta

# https://ghostty.org/docs/install/build#debian-and-ubuntu
- name: Install pre-requisite packages
  become: true
  apt:
    pkg:
      - libgtk-4-dev
      - libadwaita-1-dev
      - blueprint-compiler
      - pkg-config
      - gettext
      - git
      - stow # required for linking the config

- name: Clone
  git:
    repo: https://github.com/ghostty-org/ghostty
    dest: ~/code/ghostty/ghostty
    # version: v1.1.3
    version: tip # v1.1.2 was too buggy, v1.1.3 did not compile, settle on the next release that works
    force: true
  register: ghostty_changed

# Use snap one for now, not sure why the build is broken
- name: Install ghossty snap
  become: true
  snap:
    name: ghostty
    classic: true

# - name: Build
#   import_tasks: build.yml
#   when: ghostty_changed.before != ghostty_changed.after

- name: Ensure config folder exists
  file:
    path: ~/.config/ghostty
    state: directory

- name: Create symlinks into dotfiles
  command: stow --target ~/ ghostty
  args:
    chdir: ~/code/dotfiles
