---
# postgres-language-server https://github.com/supabase-community/postgres-language-server/releases
postgres_lsp_version: "0.25.7"
postgres_lsp_checksum: "sha256:d48346664b55b396dbc1aca4fcb0308d6e6c311803d6e4c57da2d9fc547466c4"

# sqlfmt https://github.com/tconbeer/sqlfmt/releases
sqlfmt_version: "0.32.0"

# duckdb https://github.com/duckdb/duckdb/releases
duckdb_version: "1.5.6"
duckdb_checksum: "sha256:6e89deac1ebbc36eed0291caf8b567b030c7b86ac35998f71854e22b3c5d5e2f"
