---
- name: Clean up previous build
  file:
    path: "~/code/neovim/neovim/{{ item }}"
    state: absent
  with_items:
    - build
    - .deps

- name: Make neovim
  shell: make CMAKE_BUILD_TYPE=Release
  args:
    chdir: ~/code/neovim/neovim

- name: Install neovim
  become: yes
  shell: make install
  args:
    chdir: ~/code/neovim/neovim
