---
- name: Clean up previous build
  file:
    path: "~/code/neovim/neovim/{{ item }}"
    state: absent
  with_items:
    - build
    - .deps

- name: Make neovim
  command: make CMAKE_BUILD_TYPE=Release
  args:
    chdir: ~/code/neovim/neovim

# Since the task needs to run using 'sudo' I need to get the user with which the task is run
# to get to the location of the repository. If I use '~' the shell will expand that to 'root'
# and the task will fail
- name: Install neovim
  become: yes
  command: make install
  args:
    chdir: "{{ lookup('env', 'HOME') }}/code/neovim/neovim"
