# https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites
- name: Install pre-requisite packages
  become: yes
  apt:
    pkg:
      - cmake
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - g++
      - pkg-config
      - unzip
      - curl
      - stow # required for linking the ~/.config/nvim

- name: Clone neovim nightly
  git:
    repo: https://github.com/neovim/neovim
    dest: ~/code/neovim/neovim
    version: nightly
    force: true
  register: neovim_changed

- name: Build neovim
  import_tasks: build.yml
  when: neovim_changed.before != neovim_changed.after

- name: Ensure config folder exists
  file:
    path: ~/.config/nvim
    state: directory

- name: Create symlinks into dotfiles
  shell: stow --target ~/ vim
  args:
    chdir: ~/code/dotfiles

- name: Install and update plugins
  command: nvim --headless +PlugUpgrade +PlugInstall +PlugUpdate +qall
