# https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites
- name: Install newer cmake
  pip:
    name: cmake

# neovims build expects cmake to be in /usr/bin
# installing it with pip lands it
- name: Create symbolic link to cmake
  file:
    src: /usr/local/bin/cmake
    dest: /usr/bin/cmake
    state: link

- name: Install pre-requisite packages
  apt:
    pkg:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - g++
      - pkg-config
      - unzip
      - curl

- name: Clone neovim nightly
  git:
    repo: https://github.com/neovim/neovim
    dest: ~/code/neovim/neovim
    version: nightly
    force: true
  register: neovim_changed

- name: Build neovim
  import_tasks: build.yml
  when: neovim_changed.before != neovim_changed.after

- name: Update Plugins
  command: vim +PlugUpgrade +PlugInstall +qall
