---
- name: Cleanup stale stuff
  command: git clean -xdff
  args:
    chdir: ~/code/lsp/lua/lua-language-server

- name: Cleanup stale stuff in submodules
  command: git submodule foreach git clean -xdff
  args:
    chdir: ~/code/lsp/lua/lua-language-server

- name: Make lua-language-server
  command: ./make
  args:
    chdir: ~/code/lsp/lua/lua-language-server
    creates: ~/code/lsp/lua/bin/lua-language-server
