---
- name: Cleanup stale stuff
  command: git clean -xdff
  args:
    chdir: ~/code/lsp/sumneko/lua-language-server

- name: Cleanup stale stuff in submodules
  command: git submodule foreach git clean -xdff
  args:
    chdir: ~/code/lsp/sumneko/lua-language-server

- name: Make lua-language-server part1
  command: ninja -f compile/ninja/linux.ninja
  args:
    chdir: ~/code/lsp/sumneko/lua-language-server/3rd/luamake
    creates: ~/code/lsp/sumneko/lua-language-server/3rd/luamake/bee.so

- name: Make lua-language-server part2
  command: ./3rd/luamake/luamake rebuild
  args:
    chdir: ~/code/lsp/sumneko/lua-language-server
    creates: ~/code/lsp/sumneko/bin/Linux/lua-language-server
