---
- name: Install pre-requisite packages & luarocks
  become: yes
  apt:
    pkg:
      - luarocks
      - ninja-build

- name: Install luacheck
  become: yes
  command: luarocks install luacheck
  args:
    creates: /usr/local/bin/luacheck

- name: Ensure lsp folder exists
  file:
    path: ~/code/lsp
    state: directory

# TODO they do not provide a latest release
# I can therefore not use the Github API to fetch the latest release
# information, compute its version and check whether its a new one
# how else can I get the latest release?
- name: "Clone lua-language-server {{ lsp_release_json.json.tag_name }}"
  git:
    repo: https://github.com/sumneko/lua-language-server
    dest: ~/code/lsp/sumneko/lua-language-server
    version: 2.5.3
    recursive: true
    force: true
  register: lsp_lua_changed

- name: Build Lua LSP
  import_tasks: build.yml
  when: lsp_lua_changed.before != lsp_lua_changed.after
