---
- name: Install luarocks
  become: yes
  apt:
    pkg:
      - luarocks

- name: Install luacheck
  command: luarocks --local install luacheck
  args:
    creates: ~/.luarocks/bin/luacheck

- name: Install ninja
  pip:
    name: ninja

- name: Ensure lsp folder exists
  file:
    path: ~/code/lsp
    state: directory

- name: Clone lua-language-server
  git:
    repo: https://github.com/sumneko/lua-language-server
    dest: ~/code/lsp/sumneko/lua-language-server
    recursive: true
    force: true
  register: lsp_lua_changed

- name: Build Lua LSP
  import_tasks: build.yml
  when: lsp_lua_changed.before != lsp_lua_changed.after
