---
- name: Install packages
  become: yes
  apt:
    pkg:
      - git
      - zsh
      - stow
    state: latest

# - name: Create link to my theme
#   file:
#     src: ~/code/dotfiles/teleivo.zsh-theme
#     dest: ~/.oh-my-zsh/themes/teleivo.zsh-theme
#     state: link

# Stow will not link to my zshrc if there is already one that is not a symlink
# it manages.
- name: Remove default zshrc
  file:
    path: ~/.zshrc
    state: absent

- name: Create link to zshrc in dotfiles
  command: stow --target ~/ zsh
  args:
    chdir: ~/code/dotfiles

# https://github.com/junegunn/fzf#using-git
# the zsh completion expects it to be in ~/.fzf by default
# otherwise an FZF_BASE needs to be provided. Using FZF_BASE
# did not work with alacritty when launching it, even though
# the env var was present. When launching a subshell it dit work.
# Therefore, I am sticking to the default location.
- name: Clone fzf
  git:
    repo: https://github.com/junegunn/fzf
    dest: ~/.fzf
    depth: 1
    force: true
  register: fzf_changed

- name: Install fzf
  command:
    cmd: ./install --completion --key-bindings --update-rc --no-bash --no-fish
    chdir: ~/.fzf
  when: fzf_changed.before != fzf_changed.after

- name: Clone fzf-git.sh
  git:
    repo: https://github.com/junegunn/fzf-git.sh
    dest: ~/.fzf-git
    depth: 1
    force: true

- name: Ensure fzf-scripts folders exist
  file:
    path: ~/.fzf-scripts
    state: directory

- name: Create symlinks to fzf-scripts in dotfiles
  command:
    argv:
      - stow
      - --target
      - ~/
      - --restow
      - --stow
      - fzf-scripts
  args:
    chdir: ~/code/dotfiles
