---
- name: Install packages
  become: yes
  apt:
    pkg:
      - git
      - zsh
    state: latest

- name: Clone oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    force: yes

# Note that the zshrc is linked to my home via stow

- name: Create link to my theme
  file:
    src: ~/.dotfiles/teleivo.zsh-theme
    dest: ~/.oh-my-zsh/themes/teleivo.zsh-theme
    state: link
