- name: Install packages
  become: true
  apt:
    pkg:
      - stow # required for linking the config

# bat is named batcat in debian package due to nameclash
- name: Create link to batcat
  file:
    src: /usr/bin/batcat
    dest: ~/.local/bin/bat
    state: link

- name: Ensure config folder exists
  file:
    path: ~/.config/bat
    state: directory

- name: Create symlinks into dotfiles
  command: stow --target ~/ bat
  args:
    chdir: ~/code/dotfiles

- name: Find bat config dir
  command: bat --config-dir
  register: bat_config_dir

# https://github.com/sharkdp/bat#adding-new-themes
# should not override local changes as I might be iterating on the theme
- name: Clone bat theme
  git:
    repo: https://github.com/teleivo/bat-dogrun.git
    remote: my
    dest: "{{ bat_config_dir.stdout }}/themes/bat-dogrun"
    recursive: no
    force: false
  register: bat_theme_changed

- name: Update bat cache to get theme
  command: bat cache --build
  when: bat_theme_changed.before != bat_theme_changed.after
