- name: Install packages
  become: yes
  apt:
    pkg:
      - stow # required for linking the config

- name: Ensure config folder exists
  file:
    path: ~/.config/bat
    state: directory

- name: Create symlinks into dotfiles
  command: stow --target ~/ bat
  args:
    chdir: ~/code/dotfiles

- name: Fetch latest bat release information
  uri:
    url: https://api.github.com/repos/sharkdp/bat/releases/latest
    return_content: true
  register: bat_release_json

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

# only install bat if not installed or installed version is not the latest
# released one
- name: "Install bat version {{ bat_release_json.json.tag_name }}"
  become: yes
  loop: "{{ bat_release_json.json.assets }}"
  when:
    - ('bat' not in ansible_facts.packages) or (bat_release_json.json.tag_name | regex_replace('v', ignorecase=True)) != (ansible_facts.packages['bat'][0].version)
    - item.name == "bat_" + (bat_release_json.json.tag_name | regex_replace('v', ignorecase=True)) + "_amd64.deb"
  apt:
    deb: "{{ item.browser_download_url }}"

- name: Find bat config dir
  command: bat --config-dir
  register: bat_config_dir

# https://github.com/sharkdp/bat#adding-new-themes
# should not override local changes as I might be iterating on the theme
- name: Clone bat theme
  git:
    repo: https://github.com/teleivo/bat-dogrun.git
    remote: my
    dest: "{{ bat_config_dir.stdout }}/themes/bat-dogrun"
    recursive: no
    force: false
  register: bat_theme_changed

- name: Update bat cache to get theme
  command: bat cache --build
  when: bat_theme_changed.before != bat_theme_changed.after
