- name: Install packages
  become: yes
  apt:
    pkg:
      - stow # required for linking the config

- name: Ensure config folder exists
  file:
    path: ~/.config/bat
    state: directory

- name: Create symlinks into dotfiles
  shell: stow --target ~/ bat
  args:
    chdir: ~/code/dotfiles

- name: Fetch latest bat release information
  uri:
    url: https://api.github.com/repos/sharkdp/bat/releases/latest
    return_content: true
  register: bat_release_json

# TODO is there a best practice way for doing this? Seems a bit like a hack to
# use the debug module to compute the artifact name
- name: Compute bat artifact name
  debug:
    msg: "bat_{{ bat_release_json.json.tag_name | regex_replace('v', ignorecase=True) }}_amd64.deb"
  register: bat_artifact_name

# TODO add logic so I only install it if there is a newer version
- name: "Install bat version {{ bat_release_json.json.tag_name }}"
  become: yes
  loop: "{{ bat_release_json.json.assets }}"
  when: "item.name == bat_artifact_name.msg"
  apt:
    deb: "{{ item.browser_download_url }}"

# - name: Find bat config dir
#   shell: bat --config-dir
#   register: bat_config_dir

# # TODO use correct register variable to 
# # https://github.com/sharkdp/bat#adding-new-themes
# - name: Clone bat theme
#   git:
#     repo: https://github.com/teleivo/bat-dogrun.git
#     dest: "{{ bat_config_dir }}/themes"
#     recursive: no
#     force: true
#   register: bat_theme_changed

# - name: Update bat cache to get theme
#   shell: bat cache --build
#   when: bat_theme_changed.before != bat_theme_changed.after
