- name: Install packages
  become: yes
  apt:
    pkg:
      - stow # required for linking the config

- name: Ensure config folder exists
  file:
    path: ~/.config/bat
    state: directory

- name: Create symlinks into dotfiles
  shell: stow --target ~/ bat
  args:
    chdir: ~/code/dotfiles

- name: Fetch latest bat release information
  uri:
    url: https://api.github.com/repos/sharkdp/bat/releases/latest
    return_content: true
  register: bat_release_json

# TODO using dpkg?
# - name: "Check if JDK 11 binary for {{ latest_release_json.json.name }} exists"
#   stat:
#     path: "~/.local/jdks/{{ latest_release_json.json.name }}/bin/java"
#   register: jdk_exists

# TODO add logic so I only install it if there is a newer version by checking
# the version and adding another check into the when list
- name: "Install bat version {{ bat_release_json.json.tag_name }}"
  become: yes
  loop: "{{ bat_release_json.json.assets }}"
  when:
    - item.name == "bat_" + (bat_release_json.json.tag_name | regex_replace('v', ignorecase=True)) + "_amd64.deb"
  apt:
    deb: "{{ item.browser_download_url }}"

- name: Find bat config dir
  shell: bat --config-dir
  register: bat_config_dir

- name: foo
  debug:
    var: bat_config_dir

# https://github.com/sharkdp/bat#adding-new-themes
# should not override local changes as I might be iterating on the theme
- name: Clone bat theme
  git:
    repo: https://github.com/teleivo/bat-dogrun.git
    remote: my
    dest: "{{ bat_config_dir.stdout }}/themes/bat-dogrun"
    recursive: no
    force: false
  register: bat_theme_changed

- name: Update bat cache to get theme
  shell: bat cache --build
  when: bat_theme_changed.before != bat_theme_changed.after
