---
- name: Install packages
  become: true
  apt:
    pkg:
      - postgresql-client
      - python3
      - python3-pip
      - python3-venv # for DHIS2 doc generation

- name: Ensure DHIS2 folders exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.local/dhis2
    - ~/code/dhis2/

- name: Clone DHIS2 tooling
  git:
    repo: https://github.com/teleivo/dhis2-tooling
    dest: ~/code/dhis2/tooling
    force: no
    remote: my

- name: Link to d2 docker script
  file:
    src: "{{ lookup('env', 'HOME') }}/code/dhis2/tooling/d2"
    dest: "{{ lookup('env', 'HOME') }}/bin/d2"
    state: link
