---
- name: Install packages
  become: yes
  apt:
    pkg:
      - postgresql-client
      - python3
      - python3-pip
      - python3-venv # for DHIS2 doc generation

- name: Ensure DHIS2 home folder exists
  file:
    path: ~/.local/dhis2
    state: directory
