---
- name: Install packages
  become: yes
  apt:
    pkg:
      - npm
      - openjdk-11-jdk
      - postgresql-client
      - python3
      - python3-pip
      - python3-venv # for DHIS2 doc generation

# see https://developers.dhis2.org/docs/guides/spin-up-local-instance
- name: Install yarn globally
  become: yes
  npm:
    name: yarn
    global: yes

- name: Install dhis2 CLI globally
  yarn:
    name: "@dhis2/cli"
    global: yes

- name: Ensure DHIS2 home folder exists
  file:
    path: ~/.local/dhis2
    state: directory
