---
# see https://docs.docker.com/engine/install/debian/
# TODO do https://docs.docker.com/engine/install/linux-postinstall/
- name: Add docker apt GPG key
  become: yes
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: Add docker apt repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"

- name: Install docker
  become: yes
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - containerd.io
      - docker-ce
      - docker-ce-cli

- name: Ensure Docker config/plugin folder exists
  file:
    path: ~/.docker/cli-plugins
    state: directory

- name: Fetch latest release information
  uri:
    url: https://api.github.com/repos/docker/compose/releases/latest
    return_content: true
  register: latest_release_json

# TODO only install newer version instead of always replacing the binary
- name: "Get latest (version {{ latest_release_json.json.name }})"
  loop: "{{ latest_release_json.json.assets }}"
  when:
    - item.name == "docker-compose-linux-x86_64"
  get_url:
    url: "{{ item.browser_download_url }}"
    dest: ~/.docker/cli-plugins/docker-compose
    mode: '0555'

- name: Create link to docker-compose
  become: yes
  file:
    src: "{{ lookup('env', 'HOME') }}/.docker/cli-plugins/docker-compose"
    dest: /usr/local/bin/docker-compose
    state: link
