---
# https://docs.docker.com/engine/install/debian/#install-using-the-repository
- name: Add docker apt GPG key
  become: yes
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: Add docker apt repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"

- name: Install docker
  become: yes
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - containerd.io
      - curl
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - gnupg
      - lsb-release

# TODO also fails if the user is not already in the group 'permission denied cannot lock /etc/passwd'
- name: "Add user {{ lookup('env', 'USER') }} to docker group"
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: yes

- name: Ensure Docker config/plugin folder exists
  file:
    path: ~/.docker/cli-plugins
    state: directory
