---
# https://docs.docker.com/engine/install/debian/#install-using-the-repository
- name: Add docker apt GPG key
  become: true
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: Add docker apt repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"

- name: Install docker
  become: true
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - containerd.io
      - curl
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - gnupg
      - lsb-release

# TODO also fails if the user is not already in the group 'permission denied cannot lock /etc/passwd'
- name: "Add user {{ lookup('env', 'USER') }} to docker group"
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: yes

- name: Ensure Docker config/plugin folder exists
  file:
    path: ~/.docker/cli-plugins
    state: directory

- name: Fetch latest release information of dive
  uri:
    url: https://api.github.com/repos/wagoodman/dive/releases/latest
    return_content: true
  register: dive_release_json

- name: "Install dive (version {{ dive_release_json.json.name }})"
  become: true
  apt:
    deb: https://github.com/wagoodman/dive/releases/download/{{ dive_release_json.json.tag_name }}/dive_{{ dive_release_json.json.tag_name | regex_replace('^v', '') }}_linux_amd64.deb
