- name: Install fd-find package
  become: true
  apt:
    name: fd-find
    state: "{{ apt_package_state }}"

- name: Ensure user bin directory exists
  file:
    path: ~/.local/bin
    state: directory
    mode: '0755'

- name: Create fd symlink (fdfind -> fd)
  file:
    src: /usr/bin/fdfind
    dest: ~/.local/bin/fd
    state: link
    force: true
