- name: Install fd-find
  become: true
  apt:
    name: fd-find
    state: present

- name: Ensure ~/.local/bin exists
  file:
    path: ~/.local/bin
    state: directory
    mode: '0755'

- name: Create fd symlink
  file:
    src: /usr/bin/fdfind
    dest: ~/.local/bin/fd
    state: link
