# TODO install nodejs
---
- name: Install packages
  become: true
  apt:
    pkg:
      - build-essential
      - coreutils
      - curl
      - flatpak
      - gh
      - git
      - gnupg
      - gnupg-agent
      - gpgv
      - grep
      - gzip
      - jq
      - libsecret-1-0
      - libsecret-1-dev
      - libglib2.0-dev
      - make
      - maven
      - pkg-config
      - python3
      - python3-pip
      - restic
      - ripgrep
      - rsync
      - sassc
      - snapd
      - strace
      - time
      - tmux
      - ufw
      - vim
      - wget
      - zsh
- name: Install GUI packages
  become: true
  apt:
    pkg:
      - font-manager
      - gnome-shell-pomodoro
      - gnome-software-plugin-flatpak
      - gthumb
- name: Remove packages
  become: true
  apt:
    state: absent
    pkg:
      - firefox-esr
- name: Remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes
- name: Upgrade all packages to the latest version
  become: true
  apt:
    name: "*"
    state: latest
# see https://docs.docker.com/engine/install/debian/
# TODO do https://docs.docker.com/engine/install/linux-postinstall/
- name: Add docker apt GPG key
  become: true
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present
- name: Add docker apt repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
- name: Install docker
  become: true
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - containerd.io
      - docker-ce
      - docker-ce-cli
