# TODO install nodejs
---
- name: Install packages
  become: yes
  apt:
    pkg:
      - build-essential
      - coreutils
      - curl
      - flatpak
      - gh
      - git
      - gnupg
      - gnupg-agent
      - gpgv
      - grep
      - gzip
      - jq
      - libsecret-1-0
      - libsecret-1-dev
      - libglib2.0-dev
      - make
      - maven
      - pkg-config
      - python3
      - python3-pip
      - restic
      - ripgrep
      - rsync
      - sassc
      - snapd
      - strace
      - time
      - ufw
      - vim
      - wget
      - zsh

- name: Upgrade all packages to the latest version
  become: yes
  apt:
    name: "*"
    state: latest

- name: Install docker
  import_tasks: docker.yml

- name: Install bat
  import_tasks: bat.yml

- name: Clone fzf
  git:
    repo: https://github.com/junegunn/fzf
    dest: ~/code/fzf/fzf
    depth: 1
    force: true
  register: fzf_changed

# run when changes where pulled
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html#return-values
- name: Install fzf
  shell:
    cmd: ./install --completion --key-bindings --update-rc --no-bash --no-fish
    chdir: ~/code/fzf/fzf
  when: fzf_changed.before != fzf_changed.after

- name: Install GUI related things
  import_tasks: desktop.yml

- name: Install fonts
  import_tasks: fonts.yml
