---
- name: Install packages
  become: yes
  apt:
    pkg:
      - autojump
      - build-essential
      - coreutils
      - curl
      - flatpak
      - git
      - gnupg
      - gnupg-agent
      - gpgv
      - grep
      - gzip
      - jq
      - libglib2.0-dev
      - libpam-systemd # relied on by https://github.com/liske/needrestart when systemd is detected
      - libsecret-1-0
      - libsecret-1-dev
      - make
      - maven
      - needrestart
      - pkg-config
      - python3
      - python3-pip
      - ripgrep
      - rsync
      - sassc
      - shellcheck
      - snapd
      - strace
      - time
      - ufw
      - vim
      - wget
      - xsel

- name: Upgrade all packages to the latest version
  become: yes
  apt:
    name: "*"
    state: latest

- name: Install node
  become: yes
  snap:
    name: node
    classic: yes

- name: Update npm packages
  npm:
    global: yes
    state: latest

- name: Install snap CLI tools
  become: yes
  snap:
    name:
      - exercism

- name: Install codespell linter
  pip:
    name: codespell

# - name: Install docker
#   import_tasks: docker.yml

- name: Install GitHub CLI
  import_tasks: github.yml

- name: Install fd
  import_tasks: fd.yml

- name: Install bat
  import_tasks: bat.yml

- name: Install GUI related things
  import_tasks: desktop.yml

- name: Install fonts
  import_tasks: fonts.yml

- name: Install dhis2 related things
  import_tasks: dhis2.yml

- name: Install typescript and LSPs
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - typescript
    - typescript-language-server
    - yaml-language-server
    - vscode-langservers-extracted
