---
- name: Install packages
  become: yes
  apt:
    pkg:
      - autojump
      - build-essential
      - coreutils
      - curl
      - flatpak
      - git
      - gnupg
      - gnupg-agent
      - gpgv
      - grep
      - gzip
      - jq
      - libsecret-1-0
      - libsecret-1-dev
      - libglib2.0-dev
      - make
      - maven
      - pkg-config
      - python3
      - python3-pip
      - ripgrep
      - rsync
      - sassc
      - snapd
      - strace
      - time
      - ufw
      - vim
      - wget

- name: Upgrade all packages to the latest version
  become: yes
  apt:
    name: "*"
    state: latest

- name: Install docker
  import_tasks: docker.yml

- name: Install GitHub CLI
  import_tasks: github.yml

- name: Install bat
  import_tasks: bat.yml

- name: Install GUI related things
  import_tasks: desktop.yml

- name: Install fonts
  import_tasks: fonts.yml
