---
- name: Install packages
  become: true
  apt:
    pkg:
      - bat
      - brightnessctl
      - build-essential
      - coreutils
      - curl
      - flatpak
      - git
      - gnupg
      - graphviz
      - gnupg-agent
      - gpgv
      - grep
      - grim
      - gzip
      - jq
      - kanshi
      - libglib2.0-dev
      - libpam-systemd # relied on by https://github.com/liske/needrestart when systemd is detected
      - libsecret-1-0
      - libsecret-1-dev
      - locate
      - make
      - maven
      - needrestart
      - pipx
      - pkg-config
      - python3
      - python3-pip
      - ripgrep
      - rsync
      - sassc
      - slurp
      - snapd
      - strace
      - sway
      - swaybg
      - swayidle
      - swaylock
      - time
      - ufw
      - vim
      - waybar
      - wget
      - wl-clipboard
      - wlogout
      - xdg-desktop-portal-wlr

- name: Upgrade all packages to the latest version
  become: true
  apt:
    name: "*"
    state: latest

- name: Install node
  become: true
  snap:
    name: node
    classic: yes
    channel: 22

- name: Update npm packages
  npm:
    global: yes
    state: latest

- name: Install snap CLI tools
  become: true
  snap:
    name:
      - exercism

- name: Install docker
  import_tasks: docker.yml

- name: Install GitHub CLI
  import_tasks: github.yml

- name: Install fd
  import_tasks: fd.yml

- name: Install bat
  import_tasks: bat.yml

- name: Install atuin
  import_tasks: atuin.yml

- name: Install zoxide
  import_tasks: zoxide.yml

- name: Install yazi
  import_tasks: yazi.yml

- name: Install audio and voice processing tools
  import_tasks: audio.yml

- name: Install GUI related things
  import_tasks: desktop.yml

- name: Install fonts
  import_tasks: fonts.yml

- name: Install dhis2 related things
  import_tasks: dhis2.yml

- name: Install Google Chrome
  import_tasks: google-chrome.yml
