---
- name: Install packages
  become: true
  apt:
    pkg:
      - bat
      - build-essential
      - coreutils
      - curl
      - flatpak
      - git
      - gnome-shell-extension-tiling-assistant
      - gnupg
      - gnupg-agent
      - gpgv
      - grep
      - grim
      - gzip
      - i3
      - jq
      - libglib2.0-dev
      - libpam-systemd # relied on by https://github.com/liske/needrestart when systemd is detected
      - libsecret-1-0
      - libsecret-1-dev
      - locate
      - make
      - maven
      - needrestart
      - pipx
      - pkg-config
      - python3
      - python3-pip
      - ripgrep
      - rofi
      - rsync
      - sassc
      - slurp
      - snapd
      - strace
      - sway
      - time
      - ufw
      - vim
      - wget
      - xsel

- name: Upgrade all packages to the latest version
  become: true
  apt:
    name: "*"
    state: latest

- name: Install node
  become: true
  snap:
    name: node
    classic: yes
    channel: 22

- name: Update npm packages
  npm:
    global: yes
    state: latest

- name: Install snap CLI tools
  become: true
  snap:
    name:
      - exercism

- name: Install docker
  import_tasks: docker.yml

- name: Install GitHub CLI
  import_tasks: github.yml

- name: Install fd
  import_tasks: fd.yml

- name: Install bat
  import_tasks: bat.yml

- name: Install atuin
  import_tasks: atuin.yml

- name: Install zoxide
  import_tasks: zoxide.yml

- name: Install GUI related things
  import_tasks: desktop.yml

- name: Install fonts
  import_tasks: fonts.yml

- name: Install dhis2 related things
  import_tasks: dhis2.yml
