# Vim-like navigation keybindings
[[mgr.prepend_keymap]]
on   = [ "h" ]
run  = "leave"
desc = "Go back to parent directory"

[[mgr.prepend_keymap]]
on   = [ "l" ]
run  = "enter"
desc = "Enter directory or open file"

[[mgr.prepend_keymap]]
on   = [ "j" ]
run  = "arrow 1"
desc = "Move cursor down"

[[mgr.prepend_keymap]]
on   = [ "k" ]
run  = "arrow -1"
desc = "Move cursor up"

[[mgr.prepend_keymap]]
on   = [ "g", "g" ]
run  = "arrow -99999999"
desc = "Move cursor to the top"

[[mgr.prepend_keymap]]
on   = [ "G" ]
run  = "arrow 99999999"
desc = "Move cursor to the bottom"
