db_path = "~/Documents/.atuin-history.db"
key_path = "~/Documents/.atuin-key"
session_path = "~/Documents/.atuin-session"

filter_mode = "directory"
search_mode = "fuzzy"
keymap_mode = "vim-insert"
enter_accept = true

style = "compact"
invert = true
show_help = false

scroll_exits = false

common_subcommands = [
  "apt",
  "cargo",
  "composer",
  "dnf",
  "docker",
  "git",
  "go",
  "ip",
  "kubectl",
  "nix",
  "mvn",
  "nmcli",
  "npm",
  "pecl",
  "pnpm",
  "podman",
  "port",
  "systemctl",
  "tmux",
  "yarn",
]

[theme]
name = "dogrun"
debug = true
