return {
  {
    'tpope/vim-fugitive',
    keys = {
      { '<leader>gg', ':Git<CR>', desc = 'Git summary' },
      { '<leader>gs', ':Git status --short<CR>', desc = 'Git status' },
      { '<leader>gd', ':Git diff<CR>', desc = 'Git diff' },
      { '<leader>gds', ':Git diff --staged<CR>', desc = 'Git diff staged' },
      { '<leader>gap', ':Git add -p<CR>', desc = 'Git add patch' },
      { '<leader>gc', ':Git commit -v<CR>', desc = 'Git commit' },
      { '<leader>gp', ':Git push<CR>', desc = 'Git push' },
    },
    cmd = {
      'G',
      'GBrowse',
      'Gcd',
      'Gclog',
      'Gdiffsplit',
      'Gvdiffsplit',
      'Gedit',
      'Git',
      'Glcd',
      'Gllog',
      'Gmove',
      'Gread',
      'Grename',
      'Gsplit',
      'Gtabedit',
      'Gvsplit',
      'Gwq',
      'Gwrite',
    },
    dependencies = {
      'tpope/vim-rhubarb',
    },
  },
}
