-- uncomment to generate the fzf colorscheme from vims colorscheme
-- https://github.com/junegunn/fzf/blob/master/ADVANCED.md#generating-fzf-color-theme-from-vim-color-schemes
return {
  --   {
  --     'junegunn/fzf.vim',
  --     lazy = false,
  --     dependencies = {
  --       'junegunn/fzf',
  --     },
  --     setup = function()
  --       vim.cmd([[
  -- let g:fzf_colors =
  -- \ { 'fg':         ['fg', 'Normal'],
  --   \ 'bg':         ['bg', 'Normal'],
  --   \ 'preview-bg': ['bg', 'NormalFloat'],
  --   \ 'hl':         ['fg', 'Comment'],
  --   \ 'fg+':        ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  --   \ 'bg+':        ['bg', 'CursorLine', 'CursorColumn'],
  --   \ 'hl+':        ['fg', 'Statement'],
  --   \ 'info':       ['fg', 'PreProc'],
  --   \ 'border':     ['fg', 'Ignore'],
  --   \ 'prompt':     ['fg', 'Conditional'],
  --   \ 'pointer':    ['fg', 'Exception'],
  --   \ 'marker':     ['fg', 'Keyword'],
  --   \ 'spinner':    ['fg', 'Label'],
  --   \ 'header':     ['fg', 'Comment'] }
  -- ]])
  --     end,
  --   },
}
